### ISSUE TITLE
can't using DistributedArrays

### ISSUE THREAD

**Issue by armgong** [JuliaParallel/DistributedArrays.jl#18]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4382 (2015-04-20 03:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  master/438e90b* (fork: 187 commits, 10 days)
|__/                   |  x86_64-unknown-linux-gnu

julia> using DistributedArrays
ERROR: LoadError: syntax: invalid identifier name "..."
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
while loading /home/armgong/.julia/v0.4/DistributedArrays/src/DistributedArrays.jl, in expression starting on line 94

**Comment by ViralBShah** [comment]
It has been fixed, but has to be tagged.

**Comment by armgong** [comment]
I used master branch of DistributedArrays  commit cae5ec1ac28dd8c4e5d5d7f7895e5fdb5e325533, this should be most recently version, but still have problem,maybe there still other problem?
